FROM node:22-bookworm-slim

RUN apt-get update \
	&& apt-get install -y --no-install-recommends nginx \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/app

WORKDIR /usr/src
COPY package.json package-lock.json /usr/src/
RUN npm ci

ENV PATH=/usr/src/node_modules/.bin:$PATH

WORKDIR /usr/src/app
COPY . /usr/src/app

CMD [ "npm", "test" ]
